# Generated by Django 5.0.6 on 2024-07-06 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_discount_discount_id_alter_roomrate_room_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountroomrate',
            unique_together={('room_rate', 'discount')},
        ),
    ]
