# Generated by Django 5.0.6 on 2024-07-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_discountroomrate_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='overriddenroomrate',
            unique_together={('room_rate', 'stay_date')},
        ),
    ]
